fix: print directory

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -31,7 +31,19 @@ jobs:
             az account show
 
       - name: Print current path
-        run: ls -la
+        run: ls -la -R
+
+      - name: Find main.bicep file
+        id: find_file
+        run: |
+          file_path=$(find . -name "main.bicep")
+          if [ -z "$file_path" ]; then
+            echo "main.bicep file not found"
+            exit 1
+          else
+            echo "main.bicep file found at $file_path"
+            echo "::set-output name=filepath::$file_path"
+          fi
 
       - name: Deploy Bicep template
         run: |
